camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: false

spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:h2:file:./data/camunda
#    username: sa
#    password: sa
## Uncomment the following lines to enable the h2 DB console:
#  h2:
#    console:
#      enabled: true
#      path: /console

## Uncomment the following lines to change to port number:
camunda-rest:
  url: ${CAMUNDA_REST_URL:http://localhost:8080/rest}

process:
  getMandate-information-url: https://hook.integromat.com/gt1w3vgxe0hkqnjgcrr1mfxkyvnsuyvb

config:
  email-server: localhost
  email-server-port: 1025
  email-server-user: admin@bikinibottom.ch
  email-server-password: toomanysecrets